const COUNTRY_REQUEST = "/country/REQUEST_COUNTRY";
const COUNTRY_SUCCESS = "/country/SUCCESS_COUNTRY";
const COUNTRY_FAILURE = "/country/FAILURE_COUNTRY";

export { COUNTRY_REQUEST, COUNTRY_SUCCESS, COUNTRY_FAILURE };
