const COUNTRIES_REQUEST = "/country/REQUEST_COUNTRIES";
const COUNTRIES_SUCCESS = "/country/SUCCESS_COUNTRIES";
const COUNTRIES_FAILURE = "/country/FAILURE_COUNTRIES";

const COUNTRY_REQUEST = "/country/REQUEST_COUNTRY";
const COUNTRY_SUCCESS = "/country/SUCCESS_COUNTRY";
const COUNTRY_FAILURE = "/country/FAILURE_COUNTRY";

const TIMELINE_REQUEST = "/country/REQUEST_TIMELINE";
const TIMELINE_SUCCESS = "/country/SUCCESS_TIMELINE";
const TIMELINE_FAILURE = "/country/FAILURE_TIMELINE";

export {
  COUNTRIES_REQUEST,
  COUNTRIES_SUCCESS,
  COUNTRIES_FAILURE,
  COUNTRY_REQUEST,
  COUNTRY_SUCCESS,
  COUNTRY_FAILURE,
  TIMELINE_REQUEST,
  TIMELINE_SUCCESS,
  TIMELINE_FAILURE,
};
