const COUNTRY_REQUEST = "/country/REQUEST_COUNTRY";
const COUNTRY_SUCCESS = "/country/SUCCESS_COUNTRY";
const COUNTRY_FAILURE = "/country/FAILURE_COUNTRY";

const TIMELINE_REQUEST = "/country/REQUEST_TIMELINE";
const TIMELINE_SUCCESS = "/country/SUCCESS_TIMELINE";
const TIMELINE_FAILURE = "/country/FAILURE_TIMELINE";

export {
  COUNTRY_REQUEST,
  COUNTRY_SUCCESS,
  COUNTRY_FAILURE,
  TIMELINE_REQUEST,
  TIMELINE_SUCCESS,
  TIMELINE_FAILURE,
};
