const ALL_STATS_REQUEST = "/maps/REQUEST_ALL_STATS";
const ALL_STATS_SUCCESS = "/maps/SUCCESS_ALL_STATS";
const ALL_STATS_FAILURE = "/maps/FAILURE_ALL_STATS";

export { ALL_STATS_REQUEST, ALL_STATS_SUCCESS, ALL_STATS_FAILURE };
