const ALL_STATS_REQUEST = "/dashboard/REQUEST_ALL_STATS";
const ALL_STATS_SUCCESS = "/dashboard/SUCCESS_ALL_STATS";
const ALL_STATS_FAILURE = "/dashboard/FAILURE_ALL_STATS";

const TIMELINE_REQUEST = "/dashboard/REQUEST_TIMELINE";
const TIMELINE_SUCCESS = "/dashboard/SUCCESS_TIMELINE";
const TIMELINE_FAILURE = "/dashboard/FAILURE_TIMELINE";

export {
  ALL_STATS_REQUEST,
  ALL_STATS_SUCCESS,
  ALL_STATS_FAILURE,
  TIMELINE_REQUEST,
  TIMELINE_SUCCESS,
  TIMELINE_FAILURE,
};
