const LOCATIONS_REQUEST = "/maps/REQUEST_LOCATIONS";
const LOCATIONS_SUCCESS = "/maps/SUCCESS_LOCATIONS";
const LOCATIONS_FAILURE = "/maps/FAILURE_LOCATIONS";

export { LOCATIONS_REQUEST, LOCATIONS_SUCCESS, LOCATIONS_FAILURE };
